# 🐍 Python + Pandas 🐼

#### Time Series Segmentation using .between_time()

`.between_time()` selects rows whose *time of day* falls within a given start and end time, regardless of the date. It's a handy way to split a day into segments such as early morning, morning, afternoon and evening.

In [1]:
import pandas as pd
import numpy as np

np.random.seed(0)

In [2]:
dummy_data = pd.DataFrame({
    "Temperature": np.random.randint(5, 30, size=24)
}, index=pd.date_range("2023-11-28", periods=24, freq="h"))

Split the day into four time-of-day segments.

In [3]:
early_morning_data = dummy_data.between_time("00:00", "06:00")
morning_data = dummy_data.between_time("06:00", "12:00")
afternoon_data = dummy_data.between_time("12:00", "18:00")
evening_data = dummy_data.between_time("18:00", "23:59")

In [4]:
display(early_morning_data)
display(morning_data)
display(afternoon_data)
display(evening_data)

                     Temperature
2023-11-28 00:00:00           17
2023-11-28 01:00:00           20
2023-11-28 02:00:00           26
2023-11-28 03:00:00            5
2023-11-28 04:00:00            8
2023-11-28 05:00:00            8
2023-11-28 06:00:00           12

                     Temperature
2023-11-28 06:00:00           12
2023-11-28 07:00:00           14
2023-11-28 08:00:00           24
2023-11-28 09:00:00           26
2023-11-28 10:00:00           23
2023-11-28 11:00:00            9
2023-11-28 12:00:00           28

                     Temperature
2023-11-28 12:00:00           28
2023-11-28 13:00:00           11
2023-11-28 14:00:00           29
2023-11-28 15:00:00           29
2023-11-28 16:00:00           17
2023-11-28 17:00:00            6
2023-11-28 18:00:00           11

                     Temperature
2023-11-28 18:00:00           11
2023-11-28 19:00:00           12
2023-11-28 20:00:00           28
2023-11-28 21:00:00           19
2023-11-28 22:00:00           29
2023-11-28 23:00:00           22

A few things to keep in mind:
- `.between_time()` requires the DataFrame to have a `DatetimeIndex`.
- By default both the start and end time are inclusive (controlled by the `inclusive` parameter).
- Because it matches on time of day only, it works seamlessly across multiple days in the same call.