# 🐍 Python + Pandas 🐼

#### Missing Data Imputation — bfill Update & ffill with limit

This tip is a two-part follow-up on missing data imputation: first an update on backward fill with **consecutive** gaps, then forward fill combined with the `limit` parameter.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Date": pd.date_range(start="2023-12-13", periods=7, freq="D"),
    "Temperature": [20.0, np.nan, np.nan, np.nan, 21.0, np.nan, 23.0]
}

dummy_data = pd.DataFrame(data)
dummy_data.set_index("Date", inplace=True)

### Part 1 — Backward fill (update)
With several consecutive missing values, backward fill carries the **next** valid value backward through *all* of the preceding gaps, not just the one right before it.

In [3]:
dummy_data["bfill_Temperature"] = dummy_data["Temperature"].bfill()

In [4]:
display(dummy_data)

            Temperature  bfill_Temperature
Date
2023-12-13         20.0               20.0
2023-12-14          NaN               21.0
2023-12-15          NaN               21.0
2023-12-16          NaN               21.0
2023-12-17         21.0               21.0
2023-12-18          NaN               23.0
2023-12-19         23.0               23.0

### Part 2 — Forward fill with a limit
Forward fill (`ffill`) instead carries the **previous** valid value forward. Adding `limit=1` restricts it to filling only the first missing value after a valid one, leaving any further consecutive gaps as `NaN`.

In [5]:
dummy_data["ffill_Temperature"] = dummy_data["Temperature"].ffill(limit=1)

In [6]:
display(dummy_data)

            Temperature  bfill_Temperature  ffill_Temperature
Date
2023-12-13         20.0               20.0               20.0
2023-12-14          NaN               21.0               20.0
2023-12-15          NaN               21.0                NaN
2023-12-16          NaN               21.0                NaN
2023-12-17         21.0               21.0               21.0
2023-12-18          NaN               23.0               21.0
2023-12-19         23.0               23.0               23.0

A few things to keep in mind:
- Backward fill has no built-in `limit` restriction here, so it will fill every gap it can reach with the next valid value.
- `limit=1` on forward fill means only one `NaN` after each valid value gets filled — any additional consecutive gaps stay missing.
- Use `limit` whenever filling too far from the nearest real observation would misrepresent the data.